### ISSUE TITLE
You could add zero-coverage tests

### ISSUE THREAD

**Issue by szepeviktor** [stevegrunwell/confidently-testing-wordpress#1]
I work for developer teams. I talk them into using the following zero-coverage tests in CI:

1. syntax check
2. coding standard - much more than how you indent your code
3. static analysis - [available for WordPress](https://packagist.org/packages/szepeviktor/phpstan-wordpress)

It makes your code robust without writing a single test.
So it is free, only a little compliance is necessary.

Please consider adding it to your future talk/s.

**Comment by stevegrunwell** [comment]
Hey @szepeviktor, thanks for reaching out.

I'm definitely a fan of automating all of the areas you've mentioned ([and even have a talk on CI/CD pipelines](https://stevegrunwell.com/slides/intro-to-ci-cd)), but the goal of this talk is to get developers comfortable with writing unit and integration tests, especially within the context of WordPress.

If this were to be split out into a longer talk, I'd be more than happy to cover more code quality-oriented tools, but as it stands I'm usually up against the clock as-is! 😅
